# Generated by Django 5.0.3 on 2024-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('brand', models.CharField(default='Undefined', max_length=200)),
                ('category', models.CharField(default='Undefined', max_length=200)),
                ('description', models.TextField(default=0)),
                ('thumbnail', models.CharField(default='https://tracerproducts.com/wp-content/uploads/2019/12/Product-Image-Coming-Soon.jpg', max_length=300)),
                ('image', models.CharField(default='https://tracerproducts.com/wp-content/uploads/2019/12/Product-Image-Coming-Soon.jpg', max_length=300)),
            ],
        ),
    ]
